from __future__ import annotations

CONTROLLED_INDUSTRY_LABELS: list[str] = [
    "Software",
    "Semiconductors",
    "Hardware & Devices",
    "Cloud Infrastructure",
    "Cybersecurity",
    "Internet & E-Commerce",
    "Banks",
    "Insurance",
    "Capital Markets",
    "Payments & Fintech",
    "Real Estate / REIT",
    "Oil & Gas",
    "Utilities",
    "Renewable Energy",
    "Industrial Manufacturing",
    "Aerospace & Defense",
    "Transportation & Logistics",
    "Airlines",
    "Automotive",
    "Retail",
    "Consumer Staples",
    "Restaurants",
    "Media & Entertainment",
    "Telecom",
    "Pharma & Biotech",
    "Healthcare Services",
    "Medical Devices",
    "Materials & Chemicals",
    "Mining & Metals",
    "Agriculture",
    "Education",
    "Hospitality & Travel",
    "Other",
]


# Ordered from more specific to broader categories.
KEYWORD_RULES: list[tuple[str, tuple[str, ...]]] = [
    ("Semiconductors", ("semiconductor", "chip", "micro devices", "microchip", "fab")),
    ("Cybersecurity", ("cyber", "security", "endpoint", "identity")),
    ("Cloud Infrastructure", ("cloud", "datacenter", "infrastructure", "hosting")),
    ("Payments & Fintech", ("payments", "payment", "fintech", "card", "digital wallet")),
    ("Banks", ("bank", "bancorp", "banco", "trust company")),
    ("Insurance", ("insurance", "assurance", "reinsurance")),
    ("Capital Markets", ("capital markets", "asset management", "broker", "exchange")),
    ("Real Estate / REIT", ("reit", "realty", "properties", "property trust")),
    ("Oil & Gas", ("oil", "gas", "petroleum", "drilling", "pipeline", "lng")),
    ("Utilities", ("utilities", "electric", "power", "water", "grid")),
    ("Renewable Energy", ("solar", "wind", "renewable", "battery storage", "clean energy")),
    ("Aerospace & Defense", ("aerospace", "defense", "defence", "missile", "aviation systems")),
    ("Airlines", ("airlines", "airways", "air lines", "aviation", "cargo air")),
    ("Transportation & Logistics", ("logistics", "freight", "shipping", "railroad", "transport")),
    ("Automotive", ("automotive", "motors", "vehicle", "ev", "auto")),
    ("Retail", ("retail", "stores", "department store", "marketplace", "outlet")),
    ("Consumer Staples", ("beverage", "foods", "household", "consumer products", "grocery")),
    ("Restaurants", ("restaurant", "grill", "pizza", "coffee", "cafe", "burger")),
    ("Media & Entertainment", ("media", "entertainment", "streaming", "broadcast", "gaming")),
    ("Telecom", ("telecom", "wireless", "communications", "broadband", "mobile network")),
    ("Pharma & Biotech", ("pharma", "biotech", "therapeutics", "biosciences", "oncology")),
    ("Healthcare Services", ("healthcare", "health care", "hospitals", "clinic", "managed care")),
    ("Medical Devices", ("medical device", "diagnostics", "surgical", "medtech", "imaging")),
    ("Materials & Chemicals", ("chemicals", "materials", "coatings", "specialty materials")),
    ("Mining & Metals", ("mining", "gold", "silver", "copper", "steel", "metals")),
    ("Agriculture", ("agri", "agriculture", "fertilizer", "crop", "farms")),
    ("Education", ("education", "learning", "edtech", "university")),
    ("Hospitality & Travel", ("hotel", "hospitality", "resort", "travel", "booking")),
    ("Internet & E-Commerce", ("internet", "e-commerce", "ecommerce", "online", "platform")),
    ("Hardware & Devices", ("hardware", "devices", "electronics", "instrument")),
    ("Industrial Manufacturing", ("industrial", "manufacturing", "machinery", "automation")),
    ("Software", ("software", "systems", "technologies", "solutions", "saas")),
]
